### ISSUE TITLE
ZimDroid Community

### ISSUE THREAD

**Issue by Nebucatnetzer** [hansihe/ZimDroid#2]
Hello Mr. Hans Elias J.

I've seen that you've been working on the ZimDroid application.
I've started to use Zim Wiki a few months ago and think it's a phenomenal application.
However the lack of a mobile application which can read the Zim Wiki format is quite inconvenient and in my opinion a greatly missed oportunity.

Therefore I decicded to contact all the people which have been working on the ZimDroid application to ask whether they would like to form a
small community to finish the application.
In addition I will ask on various places (reddit an the likes) if
someone would be interested in participating.

I must admit that I'm not a developer myself. However I helped for 3
years with an Android ROM project. Mostly with testing and community
work. So I'm at least somewhat familiar with developing. Beside that
I'm currently learning python which might be of use with the main Zim
Wiki application.

Please let me know if you would be interested in such a project.

Best regards

Andreas Zweili

**Comment by lrq3000** [comment]
I am also greatly interested by an android app for Zim. There is also this implementation:
https://github.com/kcg/Zim4A

A community collaboration may also be great I think.

**Comment by lrq3000** [comment]
Interesting thread discussing how to implement such an Android port of Zim:
https://bugs.launchpad.net/zim/+bug/706366

And latest attempt (2016) is here, with instructions on how to help:
https://github.com/jaap-karssenberg/zim-android-mockapp/wiki

**Comment by neoshamangames** [comment]
Is anyone actively working on this project? I might like to contribute, as I am a huge an of zim and would love to be able to have  fully-synced, full-featured version on my phone.

**Comment by lrq3000** [comment]
Have a look at https://github.com/jaap-karssenberg/zim-android-mockapp/pull/5

**Comment by Nebucatnetzer** [comment]
Hey guys, totally forgot about this.
I stopped using Zim Wiki some time ago and moved to Emacs org-mode (which is fantastic btw).
I'm going to close this issue so that someone who is still using the application can start a new try.
Please excuse the inconvenience.
